version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_esp_logger_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel-app:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_esp_logger_ngrok_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel-app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_esp_logger_ngrok_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  ngrok:
    image: ngrok/ngrok:latest
    container_name: laravel_esp_logger_ngrok
    depends_on:
      - webserver
    volumes:
      - ./docker/ngrok/ngrok.yml:/etc/ngrok.yml:ro
    command: start --config /etc/ngrok.yml --all
    networks:
      - laravel

  iot-pusher:
    build:
      context: ./iot-pusher
    container_name: iot-data-logger-client
    restart: always
    depends_on:
      - webserver
    networks:
      - laravel
    
networks:
  laravel:

volumes:
  mysql_data:
